[package]
name = "tbc"
version = "0.2.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
base64 = "0.22.1"
rand = "0.9.1"
reqwest = {version = "0.12.15", features = ["blocking"]}
thiserror = "2.0.12"
